### ISSUE TITLE
Compilation of readthedocs fails

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#1058]
The generation of the manual fails for 4 months: https://readthedocs.org/projects/lambdapi/builds/?page=2 .

**Comment by fblanqui** [comment]
Hi Abdelghani. Could you please have a look at this?

**Comment by Alidra** [comment]
Hi Frédéric,
The build has been fixed. You can have a look and approve for merge.

**Comment by fblanqui** [comment]
fix in #1059

**Comment by fblanqui** [comment]
Building the doc is still failing: https://readthedocs.org/projects/alambdapi/builds/ .
