### ISSUE TITLE
Wrong warning in scoping

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/lambdapi#341]
The following code
```
symbol A:TYPE
definition f x : A ≔ x
```
generates the following wrong warning:
```
[/home/blanqui/src/lambdapi/tmp/zo.lp, 2:13-14] Variable [x] could be replaced by [_].
```
The problem comes from the fact that the output type of f, A, indeed does not depend on x, but we should not care in this case. scope_binder should take an additional boolean argument for knowing whether a warning can be output or not.
https://github.com/Deducteam/lambdapi/blob/83ea99311b628742fa78372fb0cd13dfca5099d3/src/core/scope.ml#L251
https://github.com/Deducteam/lambdapi/blob/83ea99311b628742fa78372fb0cd13dfca5099d3/src/core/scope.ml#L267-L268

**Edit 17 March 2021:**
Here is another problematic example with a parametrized inductive type:
```
symbol Set:TYPE;
symbol τ:Set → TYPE;
symbol Prop:TYPE;
builtin "Prop" ≔ Prop;
symbol π:Prop → TYPE;
builtin "P" ≔ π;
(a:Set) inductive 𝕃:TYPE ≔
| □ : 𝕃 a
| ⸬ : τ a → 𝕃 a → 𝕃 a;
// wrong warning: [7:1-2] Variable [a] could be replaced by [_].
```

**Comment by rlepigre** [comment]
I'll have a look later, but that is going to be a bit annoying to fix since we do early desugaring in `src/core/handle.ml`. By the way, I am wondering, can the reverse situation happen? That is, is it possible that only the type `A` contains `x`, but not the term `t` in `definition f x : A ≔ t`?

**Comment by francoisthire** [comment]
> That is, is it possible that only the type A contains x, but not the term t in definition f x : A ≔ t?

Sure !

```
Definition suc n : ((fun _ -> nat) n) := S n.
```

This one is a bit exotic but I would not be surprised if a generator generates such example.

**Comment by rlepigre** [comment]
@francoisthire in your example the variable `n` appears both in the type and in the term. I was asking about an example where it would only appear in the type, not in the term.

**Comment by francoisthire** [comment]
Sorry but you can correct it easily:

```
Definition suc n : ((fun _ -> nat) n) := S 0.
```

**Comment by rlepigre** [comment]
Oh I see. Thanks @francoisthire.

**Comment by fblanqui** [comment]
I think that this is easy to fix by just adding a boolean to scope_binder. I can do it in #328.

**Comment by rlepigre** [comment]
I would prefer that you do NOT do it in #328. This has nothing to do with this PR.

**Comment by fblanqui** [comment]
Now fixed in master

**Comment by gabrielhdt** [comment]
It seems that this issue isn't solved, but you have commit something @fblanqui 45960e2.

I looked a bit but I don't understand why the `Bindlib.occur` in
https://github.com/Deducteam/lambdapi/blob/82dccc5074bd42574d8d21b9b39527052d2014cd/src/core/scope.ml#L230
returns false while `t` must be `x` itself in the top example.

**Comment by fblanqui** [comment]
Indeed, it is not fixed yet. I tried a first PR (#350) to fix it but it was not complete. The fix is not very difficult: both the type and the definition need to be bound together to know whether x does not occur at all. I will try to do this soon unless someone else wants to do it quickly.

**Comment by gabrielhdt** [comment]
To fix this issue, it seems to me that scoping should not unsugar to quickly, and scope each part of declarations on their own, potentially producing terms with free variables. This way, when scoping definition
```
symbol f x : A := x
```
we scope the body `x` as a free variable, and `A`. Later, we check that the variable `x` appears in `A` or `x`, and raise a warning in `handle.ml` if it doesn't. Finally we produce `Abst(A, \x, x)`

We may also have scoping functions that take as argument the list of variables allowed, I'm not sure yet. Do you have any opinion on this, @fblanqui?

**Comment by fblanqui** [comment]
Here is another problematic example with a parametrized inductive type:
```
symbol Set:TYPE;
symbol τ:Set → TYPE;
symbol Prop:TYPE;
builtin "Prop" ≔ Prop;
symbol π:Prop → TYPE;
builtin "P" ≔ π;
(a:Set) inductive 𝕃:TYPE ≔
| □ : 𝕃 a
| ⸬ : τ a → 𝕃 a → 𝕃 a;
// wrong warning: [7:1-2] Variable [a] could be replaced by [_].
```

**Comment by fblanqui** [comment]
We could try to implement a complete solution, at least for symbol definitions (excluding inductive types) as follows. Disable warnings when scoping a symbol declaration with both a type and a definition and at least one parameter. After scoping, we get a sequence of products and a sequence of abstractions, of the same length. We can go though them and, for each pair (product,abstraction), check that the variable occurs at least in one of them. What do you think? I can take care of this, and extend it to inductive types as well.

**Comment by gabrielhdt** [comment]
Your solution looks better indeed, and mine was a "quick-fix" anyway. I just think that this issue should be solved before making a new release.

**Comment by gabrielhdt** [comment]
I implemented your proposal in #623

**Comment by fblanqui** [comment]
Thank you Gabriel! But I am thinking now that, by doing this, we may miss some warnings. Take for instance
symbol f y : \Pi x:N, N := \lambda _, y
x is not used in N.

**Comment by gabrielhdt** [comment]
Not sure, if we go through the products and abstractions of the scoped term, we'll go through `(y: ?) -> (x: N) -> N` and `\y: ?, \_:?, y` and hence remark that `x` is not used in both expressions.

**Comment by fblanqui** [comment]
Then, there is something wrong because, clearly, `Pi x:N,N` should be written `N->N`.

Other example: with `symbol f y : (\Pi x:N,N) -> N := \lambda _, y`, you get `Pi y:?, (Pi x:N,N) -> N` and `\y:?, \_:?',y`.

**Comment by gabrielhdt** [comment]
Ah right, your last example will not raise the warning for the inner `(\Pi x: N, N)` indeed. To circumvent this, we can check for bound variables in the domains of products and abstractions as well, wouldn't it be enough?

**Comment by gabrielhdt** [comment]
And it's still better to display too few warnings than irrelevant ones.

**Comment by fblanqui** [comment]
To make this properly, we would need to call scope_binder directly with no warning but in this call only: the later calls to scope_binder from scope would warn.

**Comment by fblanqui** [comment]
We can do this as follows:
- remove the top-level definition of scope
- add to each inner function the arguments md and ss
- add an optional ~warn argument to scope_binder *not* transmitted in recursive calls
- we can then call scope_binder directly with warn=false

```
let scope_params :
     Tags.expo -> sig_state -> env -> meta IntMap.t Lazy.t -> p_term -> term =
  fun expo ss env sgm t ->
  let m = Stdlib.ref StrMap.empty in
  let md = M_Term(m, sgm, expo) in
  if Timed.(!log_enabled) then log_scop "%a" Pretty.term t;
  (* Extract the spine. *)
  let p_head, _ = get_pratt_args ss env t in
  let scope cons xs t =
    let warn = false in
    Bindlib.unbox (scope_binder ~warn md ss cons env xs (Some t)) in
  match p_head.elt with
  | P_Abst(xs,t) -> scope _Abst xs t
  | P_Prod(xs,t) -> scope _Prod xs t
  | _ -> assert false
```

**Comment by fblanqui** [comment]
Here is the complete code:
```
(* Unique pattern variable generation for wildcards in a LHS. *)
  let fresh_patt md name env =
    match md with
    | M_LHS(data) ->
    let fresh_index () =
      let i = data.m_lhs_size in
      data.m_lhs_size <- i + 1;
      let arity = Array.length env in
      Hashtbl.add data.m_lhs_arities i arity; i
    in
    begin
      match name with
      | Some(name) ->
          let i =
            try Hashtbl.find data.m_lhs_indices name with Not_found ->
            let i = fresh_index () in
            Hashtbl.add data.m_lhs_indices name i;
            Hashtbl.add data.m_lhs_names i name; i
          in
          _Patt (Some(i)) (Printf.sprintf "v%i_%s" i name) env
      | None       ->
          let i = fresh_index () in
          _Patt (Some(i)) (Printf.sprintf "v%i" i) env
    end
    | _           -> invalid_arg "fresh_patt mode must be M_LHS"

  (* Create a new metavariable of type [TYPE] for a missing domain. *)
  let _Meta_Type : mode -> env -> tbox = fun md env ->
    let vs = Env.to_tbox env in
    let a = Env.to_prod_box env _Type in
    let m = _Meta_full (Meta.fresh_box a (Array.length vs)) vs in
    (* Sanity check: only variables of [env] free in [m] if not in RHS. *)
    match md with
    | M_RHS(_) -> m
    | _        ->
      assert (Bindlib.is_closed (Bindlib.bind_mvar (Env.vars env) m)); m

(** [scope md ss env t] turns a parser-level term [t] into an actual term. The
    variables of the environment [env] may appear in [t], and the scoping mode
    [md] changes the behaviour related to certain constructors.  The signature
    state [ss] is used to hande module aliasing according to [find_qid]. *)
  let rec scope : mode -> sig_state -> env -> p_term -> tbox =
    fun md ss env t ->
    if Timed.(!log_enabled) then log_scop "%a" Pretty.term t;
    (* Extract the spine. *)
    let (p_head, args) = get_pratt_args ss env t in
    (* Check that LHS pattern variables are applied to no argument. *)
    begin
      match (p_head.elt, md) with
      | (P_Patt(_,_), M_LHS(_)) when args <> [] ->
          fatal t.pos "Pattern variables cannot be applied."
      | _                                       -> ()
    end;
    (* Scope the head and obtain the implicitness of arguments. *)
    let h = scope_head md ss env p_head in
    let impl =
      (* Check whether application is marked as explicit in head symbol. *)
      let expl = match p_head.elt with P_Iden(_,b) -> b | _ -> false in
      (* We avoid unboxing if [h] is not closed (and hence not a symbol). *)
      if expl || not (Bindlib.is_closed h) then [] else
      match Bindlib.unbox h with Symb(s) -> s.sym_impl | _ -> []
    in
    (* Scope and insert the (implicit) arguments. *)
    add_impl md ss env t.pos h impl args
  (* Build the application of [h] to [args], inserting implicit arguments. *)
  and add_impl md ss env loc h impl args =
    let appl_p_term t u = _Appl t (scope md ss env u) in
    let appl_meta t = _Appl t (scope_head md ss env (Pos.none P_Wild)) in
    match (impl, args) with
    (* The remaining arguments are all explicit. *)
    | ([]         , _      ) -> List.fold_left appl_p_term h args
    (* Only implicit arguments remain. *)
    | (true ::impl, []     ) -> add_impl md ss env loc (appl_meta h) impl []
    (* The first argument is implicit (could be [a] if made explicit). *)
    | (true ::impl, a::args) ->
        begin
          match a.elt with
          | P_Expl(a) -> add_impl md ss env loc (appl_p_term h a) impl args
          | _         -> add_impl md ss env loc (appl_meta h) impl (a::args)
        end
    (* The first argument [a] is explicit. *)
    | (false::impl, a::args) ->
        begin
          match a.elt with
          | P_Expl(_) -> fatal a.pos "Unexpected explicit argument."
          | _         -> add_impl md ss env loc (appl_p_term h a) impl args
        end
    (* The application is too "partial" to insert all implicit arguments. *)
    | (false::_   , []     ) ->
        (* NOTE this could be improved with more general implicits. *)
        fatal loc "More arguments are required to instantiate implicits."

  (* Scoping function for the domain of functions or products. *)
  and scope_domain : mode -> sig_state -> env -> p_term option -> tbox =
    fun md ss env a ->
    match (a, md) with
    | (None   , M_LHS(_)    ) -> fresh_patt md None (Env.to_tbox env)
    | ((Some({elt=P_Wild;_})|None), _           ) -> _Meta_Type md env
    | (Some(a)   , _           ) -> scope md ss env a
  (* Scoping function for binders (abstractions or produtcs). [scope_binder
     cons env params_list t] scopes [t] in the environment [env] extended with
     the parameters of [params_list]. For each parameter, a tbox is built
     using [cons] (either _Abst or _Prod). *)
  and scope_binder : ?warn:bool ->
        mode -> sig_state -> (tbox -> tbinder Bindlib.box -> tbox)
        -> Env.t -> p_params list -> p_term option -> tbox =
    fun ?(warn=true) md ss cons env params_list t ->
    let rec scope_params_list env params_list =
      match params_list with
      | [] ->
          begin
            match t with
            | Some t -> scope md ss env t
            | None -> _Meta_Type md env
          end
      | (idopts,typopt,_implicit)::params_list ->
          scope_params env idopts (scope_domain md ss env typopt) params_list
    and scope_params env idopts a params_list =
      let rec aux env idopts =
        match idopts with
        | [] -> scope_params_list env params_list
        | None::idopts ->
            let v = new_tvar "_" in
            let t = aux env idopts in
            cons a (Bindlib.bind_var v t)
        | Some id::idopts ->
            let v = new_tvar id.elt in
            let env = Env.add v a None env in
            let t = aux env idopts in
            if warn && id.elt.[0] <> '_' && not (Bindlib.occur v t) then
              wrn id.pos "Variable [%s] could be replaced by [_]." id.elt;
            cons a (Bindlib.bind_var v t)
      in aux env idopts
    in
    scope_params_list env params_list
  (* Scoping function for head terms. *)
  and scope_head : mode -> sig_state -> env -> p_term -> tbox =
    fun md ss env t ->
    match (t.elt, md) with
    | (P_Type, M_LHS(_)) -> fatal t.pos "TYPE is not allowed in a LHS."
    | (P_Type, _) -> _Type
    | (P_Iden(qid,_), M_LHS(d)) -> find_qid true d.m_lhs_prv ss env qid
    | (P_Iden(qid,_), M_Term(_,_,Privat)) -> find_qid false true ss env qid
    | (P_Iden(qid,_), M_RHS(d)) -> find_qid false d.m_rhs_prv ss env qid
    | (P_Iden(qid,_), _) -> find_qid false false ss env qid
    | (P_Wild, M_URHS(data)) ->
      let x =
        let name = Printf.sprintf "v%i" data.m_urhs_vars_nb in
        let x = new_tevar name in
        data.m_urhs_vars_nb <- data.m_urhs_vars_nb + 1;
        data.m_urhs_xvars <- (name, x) :: data.m_urhs_xvars;
        x
      in
      _TEnv (Bindlib.box_var x) (Env.to_tbox env)
    | (P_Wild, M_LHS(_)) -> fresh_patt md None (Env.to_tbox env)
    | (P_Wild, M_Patt) -> _Wild
    | (P_Wild, _) -> Env.fresh_meta_tbox env
    | (P_Meta({elt;pos},ts), M_Term(user_metas,sys_metas,_)) ->
        let m =
          match elt with
          | Name id ->
              (try StrMap.find id Stdlib.(!user_metas)
               with Not_found ->
                 (* We create a new metavariable [m1] of type [TYPE] and a new
                    metavariable [m] of name [id] and type [m1]. *)
                 let vs = Env.to_tbox env in
                 let m1 =
                   Meta.fresh (Env.to_prod env _Type) (Array.length vs) in
                 let a = Env.to_prod env (_Meta m1 vs) in
                 let m = Meta.fresh ~name:id a (Array.length vs) in
                 Stdlib.(user_metas := StrMap.add id m !user_metas); m)
          | Numb i ->
              (try IntMap.find i (Lazy.force sys_metas)
               with Not_found -> fatal pos "Unknown metavariable ?%d." i)
        in
        let ts =
          match ts with
          | None -> Env.to_tbox env (* [?M] is equivalent to [?M[env]]. *)
          | Some ts -> Array.map (scope md ss env) ts
        in
        _Meta m ts
    | (P_Meta(_,_), _) -> fatal t.pos "Metavariables are not allowed here."
    | (P_Patt(id,ts), M_LHS(d)) ->
        (* Check that [ts] are variables. *)
        let scope_var t =
          match unfold (Bindlib.unbox (scope md ss env t)) with
          | Vari(x) -> x
          | _       -> fatal t.pos "Only bound variables are allowed in the \
                                    environment of pattern variables."
        in
        let ts =
          match ts with
          | None ->
              if env = [] then [||] (* $M stands for $M[] *)
              else fatal t.pos "Missing square brackets under binder."
          | Some ts ->
              let vs = Array.map scope_var ts in
              (* Check that [vs] are distinct variables. *)
              for i = 0 to Array.length vs - 2 do
                for j = i + 1 to Array.length vs - 1 do
                  if Bindlib.eq_vars vs.(i) vs.(j) then
                    let name = Bindlib.name_of vs.(j) in
                    fatal ts.(j).pos
                      "Variable %s appears more than once \
                       in the environment of a pattern variable." name
                done
              done;
              Array.map Bindlib.box_var vs
        in
        begin
          match id with
          | None when List.length env = Array.length ts ->
              wrn t.pos
                "Pattern [%a] could be replaced by [_]." Pretty.term t;
          | Some(id) when not (List.mem id.elt d.m_lhs_in_env) ->
              if List.length env = Array.length ts then
                wrn t.pos "Pattern variable [%a] can be replaced by a \
                           wildcard [_]." Pretty.term t
              else
                wrn t.pos "Pattern variable [$%s] does not need to be \
                           named." id.elt
          | _                                                  -> ()
        end;
        fresh_patt md (Option.map (fun id -> id.elt) id) ts
    | (P_Patt(id,ts), M_URHS(r)) ->
        let x =
          match id with
          | None     -> fatal t.pos "Wildcard pattern not allowed in a URHS."
          | Some(id) ->
              (* Search in variables declared in LHS. *)
              try Hashtbl.find r.m_urhs_data id.elt
              with Not_found ->
                (* Search in variables already declared in RHS. *)
                try List.assoc id.elt r.m_urhs_xvars
                with Not_found ->
                  let name =
                    Printf.sprintf "v%i_%s" r.m_urhs_vars_nb id.elt
                  in
                  let x = new_tevar name in
                  r.m_urhs_vars_nb <- r.m_urhs_vars_nb + 1          ;
                  r.m_urhs_xvars   <- (id.elt, x) :: r.m_urhs_xvars ;
                  x
        in
        let ts =
          match ts with
          | None -> [||] (* $M stands for $M[] *)
          | Some ts -> Array.map (scope md ss env) ts
        in
        _TEnv (Bindlib.box_var x) ts
    | (P_Patt(id,ts), M_RHS(r)) ->
        let x =
          match id with
          | None     -> fatal t.pos "Wildcard pattern not allowed in a RHS."
          | Some(id) ->
              (* Search in variables declared in LHS. *)
              try Hashtbl.find r.m_rhs_data id.elt
              with Not_found -> fatal t.pos "Variable must be in LHS."
        in
        let ts =
          match ts with
          | None -> [||] (* $M stands for $M[] *)
          | Some ts -> Array.map (scope md ss env) ts
        in
        _TEnv (Bindlib.box_var x) ts
    | (P_Patt(_,_), _) ->
        fatal t.pos "Pattern variables are only allowed in rewriting rules."
    | (P_Appl(_,_), _) ->  assert false (* Unreachable. *)
    | (P_Arro(_,_), M_Patt) ->
        fatal t.pos "Implications are not allowed in a pattern."
    | (P_Arro(a,b), _) -> _Impl (scope md ss env a) (scope md ss env b)
    | (P_Abst(_,_), M_Patt) ->
        fatal t.pos "Abstractions are not allowed in a pattern."
    | (P_Abst(xs,t), _) -> scope_binder md ss _Abst env xs (Some(t))
    | (P_Prod(_,_), M_Patt) ->
        fatal t.pos "Dependent products are not allowed in a pattern."
    | (P_Prod(xs,b), _) -> scope_binder md ss _Prod env xs (Some(b))
    | (P_LLet(x,xs,a,t,u), M_Term(_))
    | (P_LLet(x,xs,a,t,u), M_URHS(_))
    | (P_LLet(x,xs,a,t,u), M_RHS(_)) ->
        let a = scope_binder md ss _Prod env xs a in
        let t = scope_binder md ss _Abst env xs (Some(t)) in
        let v = new_tvar x.elt in
        let u = scope md ss (Env.add v a (Some(t)) env) u in
        if not (Bindlib.occur v u) then
          wrn x.pos "Useless let-binding ([%s] not bound)." x.elt;
        _LLet a t (Bindlib.bind_var v u)
    | (P_LLet(_), M_LHS(_)) ->
        fatal t.pos "Let-bindings are not allowed in a LHS."
    | (P_LLet(_), M_Patt) ->
        fatal t.pos "Let-bindings are not allowed in a pattern."
    | (P_NLit(n), _) ->
        let sym_z = _Symb (Builtin.get ss t.pos "0")
        and sym_s = _Symb (Builtin.get ss t.pos "+1") in
        let rec unsugar_nat_lit acc n =
          if n <= 0 then acc else unsugar_nat_lit (_Appl sym_s acc) (n-1) in
        unsugar_nat_lit sym_z n
    | (P_Wrap(t), _) -> scope md ss env t
    | (P_Expl(_), _) -> fatal t.pos "Explicit argument not allowed here."

(** [scope ?exp ss env t] turns a parser-level term [t] into an actual term.
    The variables of the environment [env] may appear in [t]. The signature
    state [ss] is used to handle module aliasing according to [find_qid]. If
    [?exp] is {!constructor:Public}, then the term mustn't contain any private
    subterms. *)
let scope_term :
     Tags.expo -> sig_state -> env -> meta IntMap.t Lazy.t -> p_term -> term =
  fun expo ss env sgm t ->
  let m = Stdlib.ref StrMap.empty in
  Bindlib.unbox (scope (M_Term(m, sgm, expo)) ss env t)

let scope_params :
     Tags.expo -> sig_state -> env -> meta IntMap.t Lazy.t -> p_term -> term =
  fun expo ss env sgm t ->
  let m = Stdlib.ref StrMap.empty in
  let md = M_Term(m, sgm, expo) in
  if Timed.(!log_enabled) then log_scop "%a" Pretty.term t;
  (* Extract the spine. *)
  let p_head, _ = get_pratt_args ss env t in
  let scope cons xs t =
    let warn = false in
    Bindlib.unbox (scope_binder ~warn md ss cons env xs (Some t)) in
  match p_head.elt with
  | P_Abst(xs,t) -> scope _Abst xs t
  | P_Prod(xs,t) -> scope _Prod xs t
  | _ -> assert false
```

**Comment by gabrielhdt** [comment]
Ah thanks! Could you send a patch (attach the file in a message), using the result of `git diff`? With this I can just use `git am` to apply the patch and make the commit.

**Comment by gabrielhdt** [comment]
Or you make a commit locally then use `git format-patch --stdout HEAD^ > scoping.patch`

**Comment by fblanqui** [comment]
[diff.txt](https://github.com/Deducteam/lambdapi/files/6220326/diff.txt)

**Comment by fblanqui** [comment]
This needs to be reindented, and some comments need to be added too.

**Comment by gabrielhdt** [comment]
Shouldn't we remove the `meta IntMap.t Lazy.t` argument form `scope_params`?
