### ISSUE TITLE
Improve/clarify the opam situation

### ISSUE THREAD

**Issue by QGarchery** [Deducteam/lambdapi#839]
The current recommended way to install lambdapi is to pin it to the master branch by doing:
`opam pin add lambdapi https://github.com/Deducteam/lambdapi.git`

I think it would be nice to have the option to install a specific version of a release of lambdapi, doing only `opam install lambdapi`. Indeed, when lambdapi is a dependency of another project, it becomes awkward to target a "moving" web page.

For now, doing `opam install lambdapi` on switch 4.12.1 gives this error message which does not help understand the situation: 
```
[ERROR] Package conflict!
  * No agreement on the version of ocaml:
    - (invariant) → ocaml-base-compiler = 4.12.1 → ocaml = 4.12.1
    - lambdapi → earley-ocaml >= 1.0.2 → ocaml < 4.07.1
    You can temporarily relax the switch invariant with `--update-invariant'
```

In any case, doing
```
> opam pin add lambdapi https://github.com/Deducteam/lambdapi.git
[lambdapi.1.0] synchronised (git+https://github.com/Deducteam/lambdapi.git)
lambdapi is now pinned to git+https://github.com/Deducteam/lambdapi.git (version 1.0)
```
is confusing because the installed release version is 2.1, not 1.0:
```
> lambdapi --version
2.1.0-15-g1513e1d2
```

**Comment by fblanqui** [comment]
Hi @QGarchery. This is a mistake (I forgot to change README): the current recommended way to install lambdapi is to use opam. The current version is 2.1.

**Comment by fblanqui** [comment]
README fixed in 3629d0081b3b1ded717c2dd8611132d45c0e8cc4. Does this answer your question?

**Comment by QGarchery** [comment]
Hi Frédéric, thanks for your answer. This solves one part of my problem but I'm still unable to do `opam install lambdapi` (error message in my original post). What am I doing wrong ?

**Comment by fblanqui** [comment]
Could you please try to opam uninstall lambdapi and earley (lambdapi does not depend on it anymore), opam update, opam ugrade and opam install lambdapi again?

**Comment by QGarchery** [comment]
That solved it, thanks ! Since I originally did all that on a new switch, I don't really know what happened. I'm guessing its because package metadata on opam (including dependencies) are not updated when creating a new switch.
